import json

cells = [
    {
        "cell_type": "markdown",
        "id": "intro",
        "metadata": {},
        "source": [
            "# 📋 PENILAIAN KELAYAKAN KREDIT MIKRO\n",
            "### Sistem Pendukung Keputusan Berbasis Logika Fuzzy Mamdani-Sugeno + ML + DL (From Scratch)\n",
            "\n",
            "Notebook ini berisi source code lengkap untuk sistem pendukung keputusan (SPK) kelayakan kredit mikro menggunakan logika fuzzy (Mamdani dan Sugeno) yang dibuat **100% from scratch** (tanpa library fuzzy eksternal).\n",
            "Sebagai pelengkap dan pembanding, model Machine Learning (Regresi Linear) dan Deep Learning (Artificial Neural Network - MLP) juga dilatih menggunakan dataset nyata dari Kaggle.\n",
            "\n",
            "**Anggota Kelompok:**\n",
            "- Muhammad Emir Rasyad Rahman (103012400206)\n",
            "- Rizky Dzulfikar Ahmad (103012430033)\n",
            "\n",
            "**Dataset Source:** [Credit Score Classification — Kaggle](https://www.kaggle.com/datasets/parisrohan/credit-score-classification)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "sel_1",
        "metadata": {},
        "outputs": [],
        "source": [
            "# ==============================================================================\n",
            "# SEL 1: INSTALASI DAN IMPOR LIBRARY\n",
            "# ==============================================================================\n",
            "# %pip install scikit-learn pandas numpy matplotlib seaborn\n",
            "\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "import time\n",
            "import warnings\n",
            "import matplotlib.pyplot as plt\n",
            "import matplotlib.patches as mpatches\n",
            "from matplotlib.gridspec import GridSpec\n",
            "from sklearn.linear_model import LinearRegression\n",
            "from sklearn.neural_network import MLPClassifier\n",
            "from sklearn.model_selection import train_test_split\n",
            "from sklearn.preprocessing import StandardScaler\n",
            "\n",
            "warnings.filterwarnings('ignore')\n",
            "print(\"-> Sukses! Library berhasil diimpor dan siap digunakan.\")"
        ]
    },
    {
        "cell_type": "markdown",
        "id": "prep_markdown",
        "metadata": {},
        "source": [
            "## 📂 1. Load & Preprocessing Dataset\n",
            "Dataset kotor dibersihkan dari simbol, duplikat, outlier bisnis, dan baris kosong. Dari data yang valid, diambil **60.000 sampel bersih** untuk analisis dan pelatihan model."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "sel_2",
        "metadata": {},
        "outputs": [],
        "source": [
            "# ==============================================================================\n",
            "# SEL 2: LOAD & PREPROCESSING DATASET\n",
            "# ==============================================================================\n",
            "print(\"Sedang membaca dan membersihkan data train.csv...\")\n",
            "try:\n",
            "    df = pd.read_csv(\"train.csv\", low_memory=False)\n",
            "except FileNotFoundError:\n",
            "    print(\"[ERROR] File 'train.csv' tidak ditemukan! Pastikan posisinya satu folder dengan notebook ini.\")\n",
            "    raise\n",
            "\n",
            "kolom_fitur = [\n",
            "    'Annual_Income', 'Outstanding_Debt', 'Interest_Rate', \n",
            "    'Delay_from_due_date', 'Num_of_Delayed_Payment'\n",
            "]\n",
            "kolom_semua = kolom_fitur + ['Credit_Score']\n",
            "df_clean = df[kolom_semua].copy()\n",
            "\n",
            "# Pembersihan tipe data string kotor ke float murni\n",
            "for col in kolom_fitur:\n",
            "    df_clean[col] = df_clean[col].astype(str).str.replace(r'[^\\d.\\-]', '', regex=True).replace('', np.nan)\n",
            "    df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')\n",
            "\n",
            "# Mengubah nilai delay negatif menjadi 0 hari dan menghapus data kosong (NaN)\n",
            "df_clean['Delay_from_due_date'] = df_clean['Delay_from_due_date'].clip(lower=0)\n",
            "df_clean['Num_of_Delayed_Payment'] = df_clean['Num_of_Delayed_Payment'].clip(lower=0)\n",
            "df_clean.dropna(inplace=True)\n",
            "\n",
            "# Mapping target teks ke angka: Poor=0, Standard=1, Good=2\n",
            "mapping_skor = {'Poor': 0, 'Standard': 1, 'Good': 2}\n",
            "df_clean['Target_Numeric'] = df_clean['Credit_Score'].map(mapping_skor)\n",
            "df_clean.dropna(subset=['Target_Numeric'], inplace=True)\n",
            "df_clean['Target_Numeric'] = df_clean['Target_Numeric'].astype(int)\n",
            "\n",
            "# Hapus duplikat\n",
            "df_clean.drop_duplicates(inplace=True)\n",
            "\n",
            "# Filter Outlier Bisnis\n",
            "df_clean = df_clean[\n",
            "    (df_clean['Annual_Income'] >= 0) & (df_clean['Annual_Income'] <= 1500000) &\n",
            "    (df_clean['Outstanding_Debt'] >= 0) &\n",
            "    (df_clean['Interest_Rate'] >= 0) & (df_clean['Interest_Rate'] <= 35) &\n",
            "    (df_clean['Delay_from_due_date'] >= 0) &\n",
            "    (df_clean['Num_of_Delayed_Payment'] >= 0)\n",
            "]\n",
            "\n",
            "# Ambil sampel tepat 60.000 baris\n",
            "df_clean = df_clean.sample(n=min(60000, len(df_clean)), random_state=42).reset_index(drop=True)\n",
            "\n",
            "print(f\"-> Sukses! Total data bersih siap uji: {len(df_clean)} baris.\")\n",
            "print(df_clean['Credit_Score'].value_counts())\n",
            "df_clean.head(5)"
        ]
    },
    {
        "cell_type": "markdown",
        "id": "ml_markdown",
        "metadata": {},
        "source": [
            "## 🤖 2. Lapis 1 - Machine Learning & Deep Learning (Sebagai Referensi Pendukung)\n",
            "Melatih model Regresi Linear dan Jaringan Saraf Tiruan (ANN / Multi-Layer Perceptron) dengan pembagian data 80% train dan 20% test."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "sel_3",
        "metadata": {},
        "outputs": [],
        "source": [
            "# ==============================================================================\n",
            "# SEL 3: LAPIS 1 - MACHINE LEARNING & DEEP LEARNING TRAINING\n",
            "# ==============================================================================\n",
            "print(\"Membagi data dan melatih model...\")\n",
            "X = df_clean[kolom_fitur]\n",
            "y = df_clean['Target_Numeric']\n",
            "\n",
            "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
            "\n",
            "# 1. Model Regresi Linear (ML)\n",
            "model_lr = LinearRegression()\n",
            "model_lr.fit(X_train, y_train)\n",
            "\n",
            "# 2. Model Jaringan Saraf Tiruan / ANN (DL)\n",
            "scaler = StandardScaler()\n",
            "X_train_s = scaler.fit_transform(X_train)\n",
            "X_test_s = scaler.transform(X_test)\n",
            "\n",
            "model_dl = MLPClassifier(\n",
            "    hidden_layer_sizes=(64, 32, 16),\n",
            "    activation='relu',\n",
            "    max_iter=500,\n",
            "    random_state=42,\n",
            "    early_stopping=True,\n",
            "    validation_fraction=0.1\n",
            ")\n",
            "model_dl.fit(X_train_s, y_train)\n",
            "\n",
            "print(\"-> Sukses! Model Regresi Linear dan ANN/MLP berhasil dilatih.\")"
        ]
    },
    {
        "cell_type": "markdown",
        "id": "fuzzy_markdown",
        "metadata": {},
        "source": [
            "## 🔢 3. Lapis 2 - Logika Fuzzy From Scratch (34 Aturan)\n",
            "Membangun fungsi keanggotaan Segitiga dan Trapesium. Himpunan dan boundary dioptimasi agar tidak terjadi bias/error pada input bernilai 0 (suku bunga 0%, delay 0 hari)."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "sel_4",
        "metadata": {},
        "outputs": [],
        "source": [
            "# ==============================================================================\n",
            "# SEL 4: KEANGGOTAAN DAN INFERENSI FUZZY (34 ATURAN)\n",
            "# ==============================================================================\n",
            "def segitiga(x, a, b, c):\n",
            "    if x <= a or x >= c: return 0.0\n",
            "    if a < x <= b: return (x - a) / (b - a) if b != a else 1.0\n",
            "    return (c - x) / (c - b) if c != b else 1.0\n",
            "\n",
            "def trapesium(x, a, b, c, d):\n",
            "    if x < a or x > d: return 0.0\n",
            "    if a < x < b: return (x - a) / (b - a) if b != a else 1.0\n",
            "    if b <= x <= c: return 1.0\n",
            "    return (d - x) / (d - c) if d != c else 1.0\n",
            "\n",
            "def get_fuzzy_values(row):\n",
            "    inc = row['Annual_Income']\n",
            "    debt = row['Outstanding_Debt']\n",
            "    ir = row['Interest_Rate']\n",
            "    del_day = row['Delay_from_due_date']\n",
            "    num_del = row['Num_of_Delayed_Payment']\n",
            "    \n",
            "    return {\n",
            "        'inc': {\n",
            "            'Rendah': trapesium(inc, 0, 0, 30000, 50000),\n",
            "            'Sedang': segitiga(inc, 30000, 65000, 100000),\n",
            "            'Tinggi': trapesium(inc, 80000, 100000, 1500000, 2000000)\n",
            "        },\n",
            "        'debt': {\n",
            "            'Sedikit': trapesium(debt, 0, 0, 1000, 2000),\n",
            "            'Sedang':  segitiga(debt, 1000, 2500, 4000),\n",
            "            'Banyak':  trapesium(debt, 3000, 5000, 100000, 100000)\n",
            "        },\n",
            "        'ir': {\n",
            "            'Rendah': trapesium(ir, 0, 0, 8, 12),\n",
            "            'Sedang': segitiga(ir, 8, 15, 22),\n",
            "            'Tinggi': trapesium(ir, 18, 25, 35, 100)\n",
            "        },\n",
            "        'del': {\n",
            "            'Singkat': trapesium(del_day, 0, 0, 10, 20),\n",
            "            'Sedang':  segitiga(del_day, 10, 30, 45),\n",
            "            'Lama':    trapesium(del_day, 35, 60, 200, 200)\n",
            "        },\n",
            "        'num': {\n",
            "            'Jarang':   trapesium(num_del, 0, 0, 5, 8),\n",
            "            'Sering':   segitiga(num_del, 5, 12, 18),\n",
            "            'SgtSering':trapesium(num_del, 15, 25, 100, 100)\n",
            "        }\n",
            "    }\n",
            "\n",
            "def evaluate_34_rules(fz):\n",
            "    # --- OUTPUT: BAIK ---\n",
            "    r01 = min(fz['inc']['Tinggi'], fz['debt']['Sedikit'], fz['ir']['Rendah'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    r02 = min(fz['inc']['Tinggi'], fz['debt']['Sedang'],  fz['ir']['Sedang'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    r03 = min(fz['inc']['Sedang'], fz['debt']['Sedikit'], fz['ir']['Rendah'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    r04 = min(fz['inc']['Tinggi'], fz['debt']['Sedikit'], fz['ir']['Tinggi'], fz['del']['Sedang'],  fz['num']['Jarang'])\n",
            "    r16 = min(fz['inc']['Sedang'], fz['debt']['Sedikit'], fz['ir']['Sedang'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    r17 = min(fz['inc']['Tinggi'], fz['debt']['Sedang'],  fz['ir']['Rendah'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    r23 = min(fz['inc']['Tinggi'], fz['debt']['Sedikit'], fz['ir']['Sedang'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    r24 = min(fz['inc']['Sedang'], fz['debt']['Sedang'],  fz['ir']['Rendah'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    \n",
            "    # --- OUTPUT: STANDAR ---\n",
            "    r05 = min(fz['inc']['Sedang'], fz['debt']['Sedang'],  fz['ir']['Sedang'], fz['del']['Sedang'],  fz['num']['Sering'])\n",
            "    r06 = min(fz['inc']['Rendah'], fz['debt']['Sedikit'], fz['ir']['Rendah'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    r07 = min(fz['inc']['Tinggi'], fz['debt']['Banyak'],  fz['ir']['Sedang'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    r08 = min(fz['inc']['Sedang'], fz['debt']['Banyak'],  fz['ir']['Tinggi'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    r09 = min(fz['inc']['Rendah'], fz['debt']['Sedang'],  fz['ir']['Rendah'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    r10 = min(fz['inc']['Tinggi'], fz['debt']['Sedang'],  fz['ir']['Tinggi'], fz['del']['Sedang'],  fz['num']['Sering'])\n",
            "    r18 = min(fz['inc']['Sedang'], fz['debt']['Sedang'],  fz['ir']['Sedang'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    r19 = min(fz['inc']['Rendah'], fz['debt']['Sedikit'], fz['ir']['Sedang'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    r20 = min(fz['inc']['Sedang'], fz['debt']['Sedang'],  fz['ir']['Tinggi'], fz['del']['Singkat'], fz['num']['Jarang'])\n",
            "    r33 = min(fz['inc']['Sedang'], fz['debt']['Sedikit'], fz['ir']['Sedang'], fz['del']['Singkat'], fz['num']['Sering'])\n",
            "    r34 = min(fz['inc']['Tinggi'], fz['debt']['Sedikit'], fz['ir']['Sedang'], fz['del']['Singkat'], fz['num']['Sering'])\n",
            "    \n",
            "    # --- OUTPUT: BURUK ---\n",
            "    r11 = min(fz['inc']['Rendah'], fz['debt']['Banyak'],  fz['ir']['Tinggi'], fz['del']['Lama'],    fz['num']['SgtSering'])\n",
            "    r12 = min(fz['inc']['Tinggi'], fz['debt']['Banyak'],  fz['ir']['Tinggi'], fz['del']['Lama'],    fz['num']['SgtSering'])\n",
            "    r13 = min(fz['inc']['Sedang'], fz['debt']['Banyak'],  fz['ir']['Sedang'], fz['del']['Sedang'],  fz['num']['Sering'])\n",
            "    r14 = min(fz['inc']['Rendah'], fz['debt']['Sedang'],  fz['ir']['Sedang'], fz['del']['Lama'],    fz['num']['Sering'])\n",
            "    r15 = min(fz['inc']['Sedang'], fz['debt']['Sedikit'], fz['ir']['Tinggi'], fz['del']['Lama'],    fz['num']['SgtSering'])\n",
            "    r21 = min(fz['inc']['Rendah'], fz['debt']['Sedang'],  fz['ir']['Tinggi'], fz['del']['Sedang'],  fz['num']['Sering'])\n",
            "    r22 = min(fz['inc']['Sedang'], fz['debt']['Banyak'],  fz['ir']['Tinggi'], fz['del']['Lama'],    fz['num']['Sering'])\n",
            "    r25 = min(fz['inc']['Rendah'], fz['debt']['Sedang'],  fz['ir']['Tinggi'], fz['del']['Lama'],    fz['num']['Sering'])\n",
            "    r26 = min(fz['inc']['Sedang'], fz['debt']['Sedang'],  fz['ir']['Tinggi'], fz['del']['Sedang'],  fz['num']['SgtSering'])\n",
            "    r27 = min(fz['inc']['Sedang'], fz['debt']['Sedang'],  fz['ir']['Tinggi'], fz['del']['Lama'],    fz['num']['SgtSering'])\n",
            "    r28 = min(fz['inc']['Sedang'], fz['debt']['Sedang'],  fz['ir']['Tinggi'], fz['del']['Sedang'],  fz['num']['Sering'])\n",
            "    r29 = min(fz['inc']['Rendah'], fz['debt']['Sedang'],  fz['ir']['Tinggi'], fz['del']['Lama'],    fz['num']['Jarang'])\n",
            "    r30 = min(fz['inc']['Rendah'], fz['debt']['Sedang'],  fz['ir']['Tinggi'], fz['del']['Singkat'], fz['num']['Sering'])\n",
            "    r31 = min(fz['inc']['Rendah'], fz['debt']['Sedikit'], fz['ir']['Tinggi'], fz['del']['Lama'],    fz['num']['Sering'])\n",
            "    r32 = min(fz['inc']['Sedang'], fz['debt']['Sedang'],  fz['ir']['Sedang'], fz['del']['Lama'],    fz['num']['SgtSering'])\n",
            "    \n",
            "    baik = max(r01, r02, r03, r04, r16, r17, r23, r24)\n",
            "    standar = max(r05, r06, r07, r08, r09, r10, r18, r19, r20, r33, r34)\n",
            "    buruk = max(r11, r12, r13, r14, r15, r21, r22, r25, r26, r27, r28, r29, r30, r31, r32)\n",
            "    \n",
            "    return baik, standar, buruk\n",
            "\n",
            "print(\"-> Sukses! Fungsi logika fuzzy dan 34 basis aturan berhasil didefinisikan.\")"
        ]
    },
    {
        "cell_type": "markdown",
        "id": "defuzz_markdown",
        "metadata": {},
        "source": [
            "## ⚖️ 4. Algoritma Defuzzifikasi (Mamdani Centroid vs Sugeno Weighted Average)\n",
            "Mamdani menggunakan integrasi numerik diskret (centroid) pada domain output $[0, 100]$ bersolusi tinggi. Sugeno menggunakan formula rata-rata terbobot instan menggunakan singleton ($z_{\\text{Baik}}=90, z_{\\text{Standar}}=50, z_{\\text{Buruk}}=15$)."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "sel_5",
        "metadata": {},
        "outputs": [],
        "source": [
            "# ==============================================================================\n",
            "# SEL 5: ALGORITMA DEFUZZIFIKASI\n",
            "# ==============================================================================\n",
            "def defuz_mamdani(u_baik, u_standar, u_buruk, resolusi=300):\n",
            "    if u_baik == u_standar == u_buruk == 0.0:\n",
            "        return 50.0\n",
            "    points = np.linspace(0, 100, resolusi)\n",
            "    num, den = 0.0, 0.0\n",
            "    for x in points:\n",
            "        mu_b = min(u_baik, trapesium(x, 70, 85, 100, 100))\n",
            "        mu_s = min(u_standar, segitiga(x, 30, 50, 75))\n",
            "        mu_br = min(u_buruk, trapesium(x, 0, 0, 25, 45))\n",
            "        mu_max = max(mu_b, mu_s, mu_br)\n",
            "        num += x * mu_max\n",
            "        den += mu_max\n",
            "    return num / den if den != 0.0 else 50.0\n",
            "\n",
            "def defuz_sugeno(u_baik, u_standar, u_buruk):\n",
            "    z_b, z_s, z_br = 90.0, 50.0, 15.0\n",
            "    num = (u_baik * z_b) + (u_standar * z_s) + (u_buruk * z_br)\n",
            "    den = u_baik + u_standar + u_buruk\n",
            "    return num / den if den != 0.0 else 50.0\n",
            "\n",
            "print(\"-> Sukses! Metode Defuzzifikasi Mamdani & Sugeno siap dieksekusi.\")"
        ]
    },
    {
        "cell_type": "markdown",
        "id": "eval_markdown",
        "metadata": {},
        "source": [
            "## 📈 5. Eksekusi Pengujian Batch (60.000 Sampel Vectorized)\n",
            "Di bawah ini adalah implementasi inferensi fuzzy berbasis array (vectorized) menggunakan NumPy. Ini memungkinkan evaluasi fuzzy Mamdani dan Sugeno terhadap seluruh **60.000 data** dalam waktu kurang dari 5 detik."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "sel_6",
        "metadata": {},
        "outputs": [],
        "source": [
            "# ==============================================================================\n",
            "# SEL 6: EKSEKUSI BATCH VECTORIZED (60.000 BARIS)\n",
            "# ==============================================================================\n",
            "print(\"Mengevaluasi performa sistem Hybrid terhadap seluruh 60.000 data uji (Vectorized)...\")\n",
            "t0 = time.time()\n",
            "\n",
            "inc = df_clean['Annual_Income'].values\n",
            "debt = df_clean['Outstanding_Debt'].values\n",
            "ir = df_clean['Interest_Rate'].values\n",
            "dd = df_clean['Delay_from_due_date'].values\n",
            "nd = df_clean['Num_of_Delayed_Payment'].values\n",
            "y_true = df_clean['Target_Numeric'].values\n",
            "\n",
            "# Fuzzifikasi Vectorized\n",
            "def _vtr(x, a, b, c, d):\n",
            "    x = np.asarray(x, dtype=float)\n",
            "    res = np.zeros_like(x)\n",
            "    if b != a: res[(x > a) & (x < b)] = (x[(x > a) & (x < b)] - a) / (b - a)\n",
            "    res[(x >= b) & (x <= c)] = 1.0\n",
            "    if d != c: res[(x > c) & (x < d)] = (d - x[(x > c) & (x < d)]) / (d - c)\n",
            "    return res\n",
            "\n",
            "def _vsg(x, a, b, c):\n",
            "    x = np.asarray(x, dtype=float)\n",
            "    res = np.zeros_like(x)\n",
            "    if b != a: res[(x > a) & (x <= b)] = (x[(x > a) & (x <= b)] - a) / (b - a)\n",
            "    if c != b: res[(x > b) & (x < c)] = (c - x[(x > b) & (x < c)]) / (c - b)\n",
            "    res[x == b] = 1.0\n",
            "    return res\n",
            "\n",
            "fz_v = {\n",
            "    'inc':  {'Rendah': _vtr(inc,0,0,30_000,50_000), 'Sedang': _vsg(inc,30_000,65_000,100_000),\n",
            "             'Tinggi': _vtr(inc,80_000,100_000,1_500_000,2_000_000)},\n",
            "    'debt': {'Sedikit': _vtr(debt,0,0,1_000,2_000), 'Sedang': _vsg(debt,1_000,2_500,4_000),\n",
            "             'Banyak': _vtr(debt,3_000,5_000,100_000,100_000)},\n",
            "    'ir':   {'Rendah': _vtr(ir,0,0,8,12), 'Sedang': _vsg(ir,8,15,22),\n",
            "             'Tinggi': _vtr(ir,18,25,35,100)},\n",
            "    'del':  {'Singkat': _vtr(dd,0,0,10,20), 'Sedang': _vsg(dd,10,30,45),\n",
            "             'Lama': _vtr(dd,35,60,200,200)},\n",
            "    'num':  {'Jarang': _vtr(nd,0,0,5,8), 'Sering': _vsg(nd,5,12,18),\n",
            "             'SgtSering': _vtr(nd,15,25,100,100)},\n",
            "}\n",
            "\n",
            "vm = np.minimum\n",
            "def vmx(*a): return np.maximum.reduce(a)\n",
            "\n",
            "ub = vmx(vm(fz_v['inc']['Tinggi'], vm(fz_v['debt']['Sedikit'], vm(fz_v['ir']['Rendah'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Tinggi'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Sedang'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Sedikit'], vm(fz_v['ir']['Rendah'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Tinggi'], vm(fz_v['debt']['Sedikit'], vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Sedang'],  fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Sedikit'], vm(fz_v['ir']['Sedang'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Tinggi'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Rendah'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Tinggi'], vm(fz_v['debt']['Sedikit'], vm(fz_v['ir']['Sedang'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Rendah'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang']))))\n",
            ")\n",
            "us = vmx(vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Sedang'],  vm(fz_v['del']['Sedang'],  fz_v['num']['Sering'])))),\n",
            "         vm(fz_v['inc']['Rendah'], vm(fz_v['debt']['Sedikit'], vm(fz_v['ir']['Rendah'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Tinggi'], vm(fz_v['debt']['Banyak'],  vm(fz_v['ir']['Sedang'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Banyak'],  vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Rendah'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Rendah'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Tinggi'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Sedang'],  fz_v['num']['Sering'])))),\n",
            "         vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Sedang'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Rendah'], vm(fz_v['debt']['Sedikit'], vm(fz_v['ir']['Sedang'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Singkat'], fz_v['num']['Jarang'])))),\n",
            "         vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Sedikit'], vm(fz_v['ir']['Sedang'],  vm(fz_v['del']['Singkat'], fz_v['num']['Sering'])))),\n",
            "         vm(fz_v['inc']['Tinggi'], vm(fz_v['debt']['Sedikit'], vm(fz_v['ir']['Sedang'],  vm(fz_v['del']['Singkat'], fz_v['num']['Sering']))))\n",
            ")\n",
            "ubr = vmx(vm(fz_v['inc']['Rendah'], vm(fz_v['debt']['Banyak'],  vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Lama'],    fz_v['num']['SgtSering'])))),\n",
            "          vm(fz_v['inc']['Tinggi'], vm(fz_v['debt']['Banyak'],  vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Lama'],    fz_v['num']['SgtSering'])))),\n",
            "          vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Banyak'],  vm(fz_v['ir']['Sedang'],  vm(fz_v['del']['Sedang'],  fz_v['num']['Sering'])))),\n",
            "          vm(fz_v['inc']['Rendah'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Sedang'],  vm(fz_v['del']['Lama'],    fz_v['num']['Sering'])))),\n",
            "          vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Sedikit'], vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Lama'],    fz_v['num']['SgtSering'])))),\n",
            "          vm(fz_v['inc']['Rendah'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Sedang'],  fz_v['num']['Sering'])))),\n",
            "          vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Banyak'],  vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Lama'],    fz_v['num']['Sering'])))),\n",
            "          vm(fz_v['inc']['Rendah'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Lama'],    fz_v['num']['Sering'])))),\n",
            "          vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Sedang'],  fz_v['num']['SgtSering'])))),\n",
            "          vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Lama'],    fz_v['num']['SgtSering'])))),\n",
            "          vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Sedang'],  fz_v['num']['Sering'])))),\n",
            "          vm(fz_v['inc']['Rendah'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Lama'],    fz_v['num']['Jarang'])))),\n",
            "          vm(fz_v['inc']['Rendah'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Singkat'], fz_v['num']['Sering'])))),\n",
            "          vm(fz_v['inc']['Rendah'], vm(fz_v['debt']['Sedikit'], vm(fz_v['ir']['Tinggi'],  vm(fz_v['del']['Lama'],    fz_v['num']['Sering'])))),\n",
            "          vm(fz_v['inc']['Sedang'], vm(fz_v['debt']['Sedang'],  vm(fz_v['ir']['Sedang'],  vm(fz_v['del']['Lama'],    fz_v['num']['SgtSering']))))\n",
            ")\n",
            "\n",
            "# Sugeno Vectorized\n",
            "tot = ub + us + ubr\n",
            "pred_s = np.where(tot == 0, 50.0, (ub*90 + us*50 + ubr*15) / np.where(tot==0, 1, tot))\n",
            "\n",
            "# Mamdani Vectorized\n",
            "x_o = np.linspace(0, 100, 100)\n",
            "mfb = _vtr(x_o, 70, 85, 100, 100)\n",
            "mfs = _vsg(x_o, 30, 50, 75)\n",
            "mfbr = _vtr(x_o, 0, 0, 25, 45)\n",
            "mu_b = np.minimum(ub[:, np.newaxis], mfb)\n",
            "mu_s = np.minimum(us[:, np.newaxis], mfs)\n",
            "mu_r = np.minimum(ubr[:, np.newaxis], mfbr)\n",
            "mu_vec = np.maximum(np.maximum(mu_b, mu_s), mu_r)\n",
            "den_vec = mu_vec.sum(axis=1)\n",
            "pred_m = np.where(den_vec == 0, 50.0, np.dot(mu_vec, x_o) / np.where(den_vec == 0, 1.0, den_vec))\n",
            "\n",
            "# Konversi ke Kelas\n",
            "def slbl(s):\n",
            "    return np.where(s >= 70, 2, np.where(s >= 40, 1, 0))\n",
            "\n",
            "y_pred_m = slbl(pred_m)\n",
            "y_pred_s = slbl(pred_s)\n",
            "\n",
            "# Konversi Ground Truth\n",
            "gt_points = np.vectorize(lambda t: 15.0 if t==0 else (50.0 if t==1 else 90.0))(y_true)\n",
            "m_points = np.vectorize(lambda t: 15.0 if t==0 else (50.0 if t==1 else 90.0))(y_pred_m)\n",
            "s_points = np.vectorize(lambda t: 15.0 if t==0 else (50.0 if t==1 else 90.0))(y_pred_s)\n",
            "\n",
            "# Hitung Metrik\n",
            "mae_m = np.mean(np.abs(m_points - gt_points))\n",
            "mae_s = np.mean(np.abs(s_points - gt_points))\n",
            "mse_m = np.mean((m_points - gt_points)**2)\n",
            "mse_s = np.mean((s_points - gt_points)**2)\n",
            "rmse_m = np.sqrt(mse_m)\n",
            "rmse_s = np.sqrt(mse_s)\n",
            "t_eval = time.time() - t0\n",
            "\n",
            "print(f\"-> Sukses! Batch evaluation selesai dalam {t_eval:.4f} detik.\\n\")\n",
            "print(\"================== HASIL AKHIR KOMPARASI (60.000 DATA) ==================\")\n",
            "print(f\"Metrik\\t\\tMamdani\\t\\tSugeno\")\n",
            "print(f\"Akurasi\\t\\t{np.mean(y_pred_m == y_true)*100:.2f}%\\t\\t{np.mean(y_pred_s == y_true)*100:.2f}%\")\n",
            "print(f\"MAE\\t\\t{mae_m:.2f}\\t\\t{mae_s:.2f}\")\n",
            "print(f\"MSE\\t\\t{mse_m:.2f}\\t\\t{mse_s:.2f}\")\n",
            "print(f\"RMSE\\t\\t{rmse_m:.2f}\\t\\t{rmse_s:.2f}\")\n",
            "print(\"=========================================================================\")"
        ]
    },
    {
        "cell_type": "markdown",
        "id": "plot_markdown",
        "metadata": {},
        "source": [
            "## 📊 6. Visualisasi Grafik Performa & Fungsi Keanggotaan\n",
            "Di bawah ini adalah visualisasi grafik fungsi keanggotaan input dan confusion matrix untuk mengevaluasi secara visual ketepatan keputusan Mamdani vs Sugeno."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "sel_7",
        "metadata": {},
        "outputs": [],
        "source": [
            "# ==============================================================================\n",
            "# SEL 7: PLOT VISUALISASI PERFORMA & FUNGSI KEANGGOTAAN\n",
            "# ==============================================================================\n",
            "# 1. Plot Membership Functions\n",
            "fig, axs = plt.subplots(1, 2, figsize=(15, 5))\n",
            "fig.suptitle('Kurva Keanggotaan Fuzzy (Annual Income & Outstanding Debt)', fontsize=14, fontweight='bold')\n",
            "\n",
            "x_inc = np.linspace(0, 200_000, 1000)\n",
            "axs[0].plot(x_inc, _vtr(x_inc, 0, 0, 30_000, 50_000), label='Rendah')\n",
            "axs[0].plot(x_inc, _vsg(x_inc, 30_000, 65_000, 100_000), label='Sedang')\n",
            "axs[0].plot(x_inc, _vtr(x_inc, 80_000, 100_000, 200_000, 200_000), label='Tinggi')\n",
            "axs[0].set_title('Annual Income')\n",
            "axs[0].legend()\n",
            "\n",
            "x_debt = np.linspace(0, 8_000, 1000)\n",
            "axs[1].plot(x_debt, _vtr(x_debt, 0, 0, 1_000, 2_000), label='Sedikit')\n",
            "axs[1].plot(x_debt, _vsg(x_debt, 1_000, 2_500, 4_000), label='Sedang')\n",
            "axs[1].plot(x_debt, _vtr(x_debt, 3_000, 5_000, 8_000, 8_000), label='Banyak')\n",
            "axs[1].set_title('Outstanding Debt')\n",
            "axs[1].legend()\n",
            "plt.show()\n",
            "\n",
            "# 2. Plot Confusion Matrix Mamdani vs Sugeno\n",
            "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n",
            "KELAS = ['Poor', 'Standard', 'Good']\n",
            "cm_m = np.zeros((3, 3), dtype=int)\n",
            "cm_s = np.zeros((3, 3), dtype=int)\n",
            "for gt, pm_i, ps_i in zip(y_true, y_pred_m, y_pred_s):\n",
            "    cm_m[gt][pm_i] += 1\n",
            "    cm_s[gt][ps_i] += 1\n",
            "\n",
            "for ax, cm, title in zip(axes, [cm_m, cm_s], ['Confusion Matrix - Mamdani', 'Confusion Matrix - Sugeno']):\n",
            "    im = ax.imshow(cm, cmap='Blues', aspect='auto')\n",
            "    ax.set_xticks(range(3)); ax.set_yticks(range(3))\n",
            "    ax.set_xticklabels(KELAS); ax.set_yticklabels(KELAS)\n",
            "    ax.set_xlabel('Prediksi'); ax.set_ylabel('Aktual')\n",
            "    ax.set_title(title, fontweight='bold')\n",
            "    for i in range(3):\n",
            "        for j in range(3):\n",
            "            ax.text(j, i, str(cm[i, j]), ha='center', va='center', color='black', fontweight='bold')\n",
            "plt.tight_layout()\n",
            "plt.show()"
        ]
    },
    {
        "cell_type": "markdown",
        "id": "xai_markdown",
        "metadata": {},
        "source": [
            "## 💡 7. Demo Tracing & Kesimpulan Otomatis (Explainable AI - XAI)\n",
            "Demo penelusuran keputusan logika fuzzy untuk tiga profil nasabah berbeda."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "sel_8",
        "metadata": {},
        "outputs": [],
        "source": [
            "# ==============================================================================\n",
            "# SEL 8: DEMO TRACING KEPUTUSAN SKENARIO\n",
            "# ==============================================================================\n",
            "def tracing_nasabah(pendapatan, utang, bunga, jeda, frekuensi, label):\n",
            "    row = {\n",
            "        'Annual_Income': pendapatan, 'Outstanding_Debt': utang,\n",
            "        'Interest_Rate': bunga, 'Delay_from_due_date': jeda, 'Num_of_Delayed_Payment': frekuensi\n",
            "    }\n",
            "    fz = get_fuzzy_values(row)\n",
            "    b, s, br = evaluate_34_rules(fz)\n",
            "    skor_m = defuz_mamdani(b, s, br)\n",
            "    skor_s = defuz_sugeno(b, s, br)\n",
            "    \n",
            "    print(f\"=== TRACING SKENARIO: {label} ===\")\n",
            "    print(f\"  Input: Income=${pendapatan:,}, Debt=${utang:,}, Bunga={bunga}%, Delay={jeda} hari, Freq={frekuensi} kali\")\n",
            "    print(f\"  Kekuatan Konsekuensi: Baik={b:.4f}, Standar={s:.4f}, Buruk={br:.4f}\")\n",
            "    print(f\"  Skor Mamdani : {skor_m:.2f} -> Kategori: {'BAIK' if skor_m >= 70 else ('STANDAR' if skor_m >= 40 else 'BURUK')}\")\n",
            "    print(f\"  Skor Sugeno  : {skor_s:.2f} -> Kategori: {'BAIK' if skor_s >= 70 else ('STANDAR' if skor_s >= 40 else 'BURUK')}\")\n",
            "    print(\"-\"*60)\n",
            "\n",
            "tracing_nasabah(120_000, 500, 5, 2, 0, \"Nasabah Risiko Rendah (BAIK)\")\n",
            "tracing_nasabah(50_000, 2_800, 14, 18, 7, \"Nasabah Risiko Menengah (STANDAR)\")\n",
            "tracing_nasabah(18_000, 7_500, 28, 50, 20, \"Nasabah Risiko Tinggi (BURUK)\")"
        ]
    }
]

notebook_data = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (ipykernel)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.13.5"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open("TUBES DKA.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook_data, f, indent=1, ensure_ascii=False)

print("[SUCCESS] Fully vectorized notebook with visualisations generated!")
